### ISSUE TITLE
Add CraftTweaker support to new crafting stations

### ISSUE THREAD

**Issue by Sixdd6** [MincraftEinstein/CutAndColored#1]
I'd like to request adding CraftTweaker support for the new crafting stations.

**Comment by MincraftEinstein** [comment]
Hello. sorry to take so long been a bit busy. by crafting stations do you mean the sawmill, the glasscutter, and the weaver? if so then I have already done that 🙂

**Comment by Sixdd6** [comment]
Oh, fantastic! I look forward to using it then 😄
