### ISSUE TITLE
Sawmill, Weaver and Glasscutter crashes game when I try to craft with them

### ISSUE THREAD

**Issue by Kaligraphy22** [MincraftEinstein/CutAndColored#2]
[crash-2021-05-09_16.08.24-server.txt](https://github.com/MincraftEinstein/CutAndColored/files/6448422/crash-2021-05-09_16.08.24-server.txt)

Hey there. As the title says, I'll put glass in the Glasscutter and when I try to craft glass bottles, the game crashes. It doesn't mater if I shift clicked them either. As I was typing this, I tried to make glass panes with the glass cutter. More crashing. I am using Cut And Colored 5.0 1.16.5 and Einsteins Library 2.0 1.16.5 in Minecraft 1.16.5 (forge version - 1.16.5-36.1.13). I have many other mods in my world as well. Let me know if you want the full list.

Edit: I changed the title of this report cause I decided to test all three blocks and all three are crashing when I craft with them. Also, added the crash log.

**Comment by MincraftEinstein** [comment]
Thanks for reporting the bug, I have just fixed it 😊.
